# docker run --detach --name=syntect_server -p 9238:9238 sourcegraph/syntect_server
# docker pull exadra37/sublime-text-3
# docker pull jamesnetherton/docker-atom-editor

# vscode -> sublime -> syntect
# .tmLanguage -> .sublime-syntax -> .packdump

version: "3"
services:

  bat:
    image: bat
    build: { context: docker, dockerfile: syntect.dockerfile }
    entrypoint: [bat]
    environment: { HOME: /root }
    volumes:
      - ./examples:/examples:ro
      - ./dist/syntect:/root/.cache/bat:ro

  packdump:
    depends_on: [bat]
    image: bat
    entrypoint: [bat]
    command: [cache, --build, --source, dist/syntect, --target, dist/syntect]
    volumes:
      - ./dist/syntect:/dist/syntect:rw

  # The service name is same as `subl --command <name>` for converting .tmLanguage
  convert_syntax:
    build: { context: docker, dockerfile: sublime.dockerfile }
    entrypoint: [./bin/sublime_syntax_convertor]
    command: [/dist/Scdlang.tmLanguage]
    volumes:
      - ./dist:/dist:rw

  dhall:
    image: dhall
    build: { context: docker, dockerfile: dhall.dockerfile }
    network_mode: host
    entrypoint: [dhall]
    volumes:
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro
  
  dhall-json:
    depends_on: [dhall]
    image: dhall
    network_mode: host
    entrypoint: [dhall-to-json]
    command: [--file, syntaxes/Scdlang.tmLanguage.dhall, --pretty, --output, dist/Scdlang.tmLanguage.json, --omitEmpty]
    volumes:
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro

  yaml-dhall:
    depends_on: [dhall]
    image: dhall
    network_mode: host
    entrypoint: [yaml-to-dhall]
    command: [syntaxes/Schema.dhall, --file, syntaxes/Scdlang.YAML-tmLanguage, --output, syntaxes/Scdlang.YAML-tmLanguage.dhall]
    volumes:
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro