# docker run --detach --name=syntect_server -p 9238:9238 sourcegraph/syntect_server
# docker pull exadra37/sublime-text-3
# docker pull jamesnetherton/docker-atom-editor

# vscode -> sublime -> syntect
# .tmLanguage -> .sublime-syntax -> .packdump

version: "3"
services:

  bat:
    image: bat
    build: { context: ., dockerfile: docker/syntect.dockerfile }
    entrypoint: [bat]
    environment: { HOME: /root }
    volumes:
      - ./examples:/examples:ro
      - ./dist/syntect:/root/.cache/bat:ro

  packdump:
    depends_on: [bat]
    image: bat
    entrypoint: [bat]
    command: [cache, --build, --source, dist/syntect, --target, dist/syntect]
    volumes:
      - ./dist/syntect:/dist/syntect:rw

  dhall-yaml:
    depends_on: [dhall]
    image: dhall
    network_mode: host
    entrypoint: [dhall2yaml]
    command: [--omitEmpty, --file, syntaxes/Scdlang.sublime-syntax.dhall, dist/Scdlang.sublime-syntax]
    volumes:
      - ./scripts/dhall2yaml.sh:/bin/dhall2yaml:ro
      - $HOME/.cache:/.cache:rw
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro

  dhall:
    image: dhall
    build: { context: ., dockerfile: docker/dhall.dockerfile }
    network_mode: host
    entrypoint: [dhall]
    volumes:
      - $HOME/.cache:/.cache:rw
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro

  dhall-encode:
    image: dhall
    build: { context: ., dockerfile: docker/dhall.dockerfile }
    network_mode: host
    entrypoint: [dhall-encode]
    command: [--input, syntaxes/Scdlang.$extension.dhall, --output, dist/Scdlang.DHALL-$extension.bin]
    volumes:
      - ./scripts/dhall-encode.sh:/bin/dhall-encode:ro
      - $HOME/.cache:/.cache:rw
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro

  dhall-json:
    depends_on: [dhall]
    image: dhall
    network_mode: host
    entrypoint: [dhall-to-json]
    command: [--file, syntaxes/Scdlang.tmLanguage.dhall, --pretty, --output, dist/Scdlang.tmLanguage.json, --omitEmpty]
    volumes:
      - $HOME/.cache:/.cache:rw
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro

  yaml-dhall:
    depends_on: [dhall]
    image: dhall
    network_mode: host
    entrypoint: [yaml-to-dhall]
    command: [syntaxes/Schema.dhall, --file, syntaxes/Scdlang.YAML-tmLanguage, --output, syntaxes/Scdlang.YAML-tmLanguage.dhall]
    volumes:
      - ./dist:/dist:rw
      - ./syntaxes:/syntaxes:ro